dist: trusty
sudo: required
language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
node_js: "5.6"
jdk: oraclejdk7
script:
  - sbt scripted sbt-typescript/ignoreCanNotFindModule
  - sbt scripted sbt-typescript/inlinesourcemap
  - sbt scripted sbt-typescript/sourcemap

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm